@protocol = http
@hostname = 127.0.0.1
@port = 3000
@host = {{protocol}}://{{hostname}}:{{port}}

###

GET {{host}}/transactions

###

GET {{host}}/transactions/pagination?pageSize=5&pageNumber=2
###

GET {{host}}/transactions/pagination?pageSize=5&pageNumber=1
###

GET {{host}}/carts/ HTTP/1.1

###

GET {{host}}/carts/1 HTTP/1.1

###

GET {{host}}/carts/price=20 HTTP/1.1

###

POST {{host}}/carts/ HTTP/1.1
content-type: application/json

{
  "data": {
    "amount": 1,
    "date": "13:11:02 13.23.2020",
    "price": 100,
    "product": "chips",
    "userId": 6
  },
  "id": 3
}

###

PUT {{host}}/carts/1 HTTP/1.1
content-type: application/json

{
  "amount": 3,
  "date": "13:11:02 13.23.2020",
  "price": 600,
  "product": "bear",
  "userId": 2
}

###

DELETE {{host}}/carts/2 HTTP/1.1

